# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/anzhelika/projekt/diplom/debug_progectv5/debug_sha3/debug_sha3.srcs/sources_1/bd/diagramm/ip/diagramm_processing_system7_0_0/diagramm_processing_system7_0_0.xci
# IP: The module: 'diagramm_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anzhelika/projekt/diplom/debug_progectv5/debug_sha3/debug_sha3.srcs/sources_1/bd/diagramm/ip/diagramm_processing_system7_0_0/diagramm_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'diagramm_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/anzhelika/projekt/diplom/debug_progectv5/debug_sha3/debug_sha3.srcs/sources_1/bd/diagramm/ip/diagramm_processing_system7_0_0/diagramm_processing_system7_0_0.xci
# IP: The module: 'diagramm_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/anzhelika/projekt/diplom/debug_progectv5/debug_sha3/debug_sha3.srcs/sources_1/bd/diagramm/ip/diagramm_processing_system7_0_0/diagramm_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'diagramm_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
