# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/diagramm/diagramm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagramm || ORIG_REF_NAME==diagramm} -quiet] -quiet

# IP: bd/diagramm/ip/diagramm_processing_system7_0_0/diagramm_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagramm_processing_system7_0_0 || ORIG_REF_NAME==diagramm_processing_system7_0_0} -quiet] -quiet

# IP: bd/diagramm/ip/diagramm_ip_sha3v5_0_0/diagramm_ip_sha3v5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagramm_ip_sha3v5_0_0 || ORIG_REF_NAME==diagramm_ip_sha3v5_0_0} -quiet] -quiet

# IP: bd/diagramm/ip/diagramm_ps7_0_axi_periph_0/diagramm_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagramm_ps7_0_axi_periph_0 || ORIG_REF_NAME==diagramm_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/diagramm/ip/diagramm_rst_ps7_0_250M_0/diagramm_rst_ps7_0_250M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagramm_rst_ps7_0_250M_0 || ORIG_REF_NAME==diagramm_rst_ps7_0_250M_0} -quiet] -quiet

# IP: bd/diagramm/ip/diagramm_auto_pc_0/diagramm_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==diagramm_auto_pc_0 || ORIG_REF_NAME==diagramm_auto_pc_0} -quiet] -quiet

# XDC: bd/diagramm/diagramm_ooc.xdc
